spring.application.name=inventory-sync-api
# Configuración de Base de Datos H2 (En memoria)
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola para ver los datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar los comandos SQL en la consola (para debugear como Senior)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
