spring.datasource.url=jdbc:postgresql://db:5432/inventorydb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=secret
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.h2.console.enabled=false